# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frec(object):
    def setupUi(self, Frec):
        Frec.setObjectName("Frec")
        Frec.resize(678, 439)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/appicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frec.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(Frec)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_newbie = QtWidgets.QWidget()
        self.tab_newbie.setObjectName("tab_newbie")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_newbie)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_newbie)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lne_firstName = QtWidgets.QLineEdit(self.groupBox)
        self.lne_firstName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lne_firstName.setObjectName("lne_firstName")
        self.gridLayout_5.addWidget(self.lne_firstName, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBox_department = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_department.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBox_department.setObjectName("comboBox_department")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.comboBox_department.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_department, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.lne_mobileCyp = QtWidgets.QLineEdit(self.groupBox)
        self.lne_mobileCyp.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lne_mobileCyp.setObjectName("lne_mobileCyp")
        self.gridLayout_5.addWidget(self.lne_mobileCyp, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.lne_lastName = QtWidgets.QLineEdit(self.groupBox)
        self.lne_lastName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lne_lastName.setObjectName("lne_lastName")
        self.gridLayout_5.addWidget(self.lne_lastName, 1, 1, 1, 1)
        self.lne_mobileOther = QtWidgets.QLineEdit(self.groupBox)
        self.lne_mobileOther.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lne_mobileOther.setObjectName("lne_mobileOther")
        self.gridLayout_5.addWidget(self.lne_mobileOther, 5, 1, 1, 1)
        self.lne_email = QtWidgets.QLineEdit(self.groupBox)
        self.lne_email.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lne_email.setObjectName("lne_email")
        self.gridLayout_5.addWidget(self.lne_email, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.btn_register = QtWidgets.QPushButton(self.tab_newbie)
        self.btn_register.setObjectName("btn_register")
        self.gridLayout_2.addWidget(self.btn_register, 2, 0, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.tab_newbie)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout_2.addWidget(self.btn_clear, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 2)
        self.checkBox_saveLocal = QtWidgets.QCheckBox(self.tab_newbie)
        self.checkBox_saveLocal.setObjectName("checkBox_saveLocal")
        self.gridLayout_2.addWidget(self.checkBox_saveLocal, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_newbie, "")
        self.tab_members = QtWidgets.QWidget()
        self.tab_members.setObjectName("tab_members")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_members)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_export = QtWidgets.QPushButton(self.tab_members)
        self.btn_export.setObjectName("btn_export")
        self.gridLayout_3.addWidget(self.btn_export, 1, 2, 1, 1)
        self.btn_delete = QtWidgets.QPushButton(self.tab_members)
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout_3.addWidget(self.btn_delete, 1, 0, 1, 1)
        self.btn_import = QtWidgets.QPushButton(self.tab_members)
        self.btn_import.setObjectName("btn_import")
        self.gridLayout_3.addWidget(self.btn_import, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_members)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab_members, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 6, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.btn_connectDb = QtWidgets.QPushButton(self.tab)
        self.btn_connectDb.setObjectName("btn_connectDb")
        self.gridLayout_4.addWidget(self.btn_connectDb, 2, 0, 1, 2)
        self.lne_dbName = QtWidgets.QLineEdit(self.tab)
        self.lne_dbName.setReadOnly(True)
        self.lne_dbName.setObjectName("lne_dbName")
        self.gridLayout_4.addWidget(self.lne_dbName, 0, 1, 1, 1)
        self.btn_exportAsCVS = QtWidgets.QPushButton(self.tab)
        self.btn_exportAsCVS.setObjectName("btn_exportAsCVS")
        self.gridLayout_4.addWidget(self.btn_exportAsCVS, 3, 0, 1, 2)
        self.btn_createDesktopEntry = QtWidgets.QPushButton(self.tab)
        self.btn_createDesktopEntry.setObjectName("btn_createDesktopEntry")
        self.gridLayout_4.addWidget(self.btn_createDesktopEntry, 4, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.lbl_dbConnection = QtWidgets.QLabel(self.centralWidget)
        self.lbl_dbConnection.setObjectName("lbl_dbConnection")
        self.gridLayout.addWidget(self.lbl_dbConnection, 0, 0, 1, 1)
        Frec.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Frec)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 678, 23))
        self.menuBar.setObjectName("menuBar")
        Frec.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(Frec)
        self.statusBar.setObjectName("statusBar")
        Frec.setStatusBar(self.statusBar)

        self.retranslateUi(Frec)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Frec)

    def retranslateUi(self, Frec):
        _translate = QtCore.QCoreApplication.translate
        Frec.setWindowTitle(_translate("Frec", "Freg"))
        self.groupBox.setTitle(_translate("Frec", "Registration Form"))
        self.label_4.setText(_translate("Frec", "E-mail"))
        self.comboBox_department.setItemText(0, _translate("Frec", "Computer Engineering"))
        self.comboBox_department.setItemText(1, _translate("Frec", "Electrical and Electronics Engineering"))
        self.comboBox_department.setItemText(2, _translate("Frec", "Mechanical Engineering"))
        self.comboBox_department.setItemText(3, _translate("Frec", "Petroleum and Natural Gas Engineering"))
        self.comboBox_department.setItemText(4, _translate("Frec", "Aerospace Engineering"))
        self.comboBox_department.setItemText(5, _translate("Frec", "Chemical Engineering"))
        self.comboBox_department.setItemText(6, _translate("Frec", "Civil Engineering"))
        self.comboBox_department.setItemText(7, _translate("Frec", "Business Administration"))
        self.comboBox_department.setItemText(8, _translate("Frec", "Economics"))
        self.comboBox_department.setItemText(9, _translate("Frec", "Political Science and International Relations"))
        self.comboBox_department.setItemText(10, _translate("Frec", "Computer Education and Instructional Technology"))
        self.comboBox_department.setItemText(11, _translate("Frec", "Guidance and Psychological Counseling"))
        self.comboBox_department.setItemText(12, _translate("Frec", "Teaching English as a Foreign Language"))
        self.comboBox_department.setItemText(13, _translate("Frec", "Psychology"))
        self.label_6.setText(_translate("Frec", "Mobile No Other "))
        self.label_5.setText(_translate("Frec", "Mobile No CYP "))
        self.label.setText(_translate("Frec", "Name"))
        self.label_3.setText(_translate("Frec", "Department"))
        self.label_2.setText(_translate("Frec", "Surname"))
        self.btn_register.setText(_translate("Frec", "Register"))
        self.btn_clear.setText(_translate("Frec", "Clear"))
        self.checkBox_saveLocal.setText(_translate("Frec", "Non-database mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_newbie), _translate("Frec", "Newbie"))
        self.btn_export.setText(_translate("Frec", "Export"))
        self.btn_delete.setText(_translate("Frec", "Delete"))
        self.btn_import.setText(_translate("Frec", "Import"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Frec", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Frec", "Surname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Frec", "E-mail"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Frec", "Department"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Frec", "Mobile No Cyp"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Frec", "Mobile No Other"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_members), _translate("Frec", "Members"))
        self.label_7.setText(_translate("Frec", "Database Name"))
        self.btn_connectDb.setText(_translate("Frec", "Connect Database"))
        self.lne_dbName.setText(_translate("Frec", "Freg_test"))
        self.btn_exportAsCVS.setText(_translate("Frec", "Export As CVS"))
        self.btn_createDesktopEntry.setText(_translate("Frec", "Create Desktop Entry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Frec", "Settings"))
        self.lbl_dbConnection.setText(_translate("Frec", "Database connection is established."))

